Feature Engineering (Standardization)  :-----

In [10]:
import seaborn as sns
import numpy as np
import pandas as pd

Loads the built-in restaurant tips dataset into a Pandas DataFrame.

In [17]:
df = sns.load_dataset('tips')
df.head(1)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2

In [12]:
total_bill = list(df['total_bill'])

In [13]:
mean=np.mean(total_bill)
std=np.std(total_bill)
print(mean,std)

19.78594262295082 8.884150577771132

In [14]:
standardized_data = []
for i in total_bill:
    z_score = (i - mean) / std
    standardized_data.append(z_score)

In [19]:
new_standardized_data=pd.DataFrame(standardized_data,columns=['total_bill'])

In [23]:
df_new=pd.concat([df,new_standardized_data],axis=1)

In [24]:
df_new.head(5)

   total_bill   tip     sex smoker  day    time  size  total_bill
0       16.99  1.01  Female     No  Sun  Dinner     2   -0.314711
1       10.34  1.66    Male     No  Sun  Dinner     3   -1.063235
2       21.01  3.50    Male     No  Sun  Dinner     3    0.137780
3       23.68  3.31    Male     No  Sun  Dinner     2    0.438315
4       24.59  3.61  Female     No  Sun  Dinner     4    0.540745

HERE, YOU CAN SEE THE NEW COLUMNS ADD IN THE DATAFRAME WITH ALL THE STANDARDIZED VALUE