Unit Vector Feature Scaling:----

In [6]:
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import normalize

Load IRIS Dataset

In [7]:
df = sns.load_dataset('iris')
df.head(3)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [8]:
features = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
scaled_array = normalize(df[features])

In [11]:
new_scaled_array=pd.DataFrame(scaled_array,columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
df_new=pd.concat([df,new_scaled_array],axis=1)

In [12]:
df_new.head(3)

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_length,sepal_width,petal_length,petal_width
0,5.1,3.5,1.4,0.2,setosa,0.803773,0.551609,0.220644,0.031521
1,4.9,3.0,1.4,0.2,setosa,0.828133,0.507020,0.236609,0.033801
2,4.7,3.2,1.3,0.2,setosa,0.805333,0.548312,0.222752,0.034269